name: Build NSS Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up OpenWrt build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip python3

    - name: Clone OpenWrt source
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        git checkout v23.05.5

    - name: Copy NSS packages
      run: |
        cp -r ${{ github.workspace }}/nss-packages/* openwrt/package/

    - name: Update and install feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure build
      run: |
        cd openwrt
        make menuconfig
        echo "CONFIG_PACKAGE_kmod-qca-nss-drv=y" >> .config
        echo "CONFIG_PACKAGE_kmod-qca-nss-ecm=y" >> .config
        echo "CONFIG_PACKAGE_kmod-qca-nss-dp=y" >> .config
        echo "CONFIG_PACKAGE_kmod-qca-nss-crypto=y" >> .config

    - name: Build NSS packages
      run: |
        cd openwrt
        make package/nss/compile V=s

    - name: Upload packages
      uses: actions/upload-artifact@v2
      with:
        name: nss-packages
        path: openwrt/bin/packages
